export const SUPPORTED_LOCALES = ["ru", "en"];
export const DEFAULT_LOCALE = "ru";

const messages = {
  en: {
    automatedProcessing: "Automated settlement processing",
    appTitle: "Settlement Register",
    appSubtitle: "A paper-sized prototype for supplier and contractor settlements.",
    metaDescription: "Synthetic supplier and contractor settlement register prototype",
    preparingConnection: "Preparing connection",
    checkingConfiguration: "Checking whether this deployment has Firebase configuration.",
    firebaseOperatorSignIn: "Firebase operator sign-in",
    syntheticAccountHint: "Use the synthetic account provisioned for this isolated project.",
    localDemoFallback: "Local demo fallback",
    localFallbackHint: "Firebase configuration is not present; records stay in this browser only.",
    operatorEmail: "Operator email",
    password: "Password",
    signInWithFirebase: "Sign in with Firebase",
    enterLocalDemo: "Enter local demo",
    syntheticPasswordHint: "Use only the synthetic operator account. Passwords are never stored by this application.",
    supplierContractorSettlements: "Supplier and contractor settlements",
    operator: "Operator",
    reset: "Reset",
    resetLocalSyntheticData: "Reset local synthetic data",
    exit: "Exit",
    primaryNavigation: "Primary navigation",
    overview: "Overview",
    counterparties: "Counterparties",
    contracts: "Contracts",
    obligations: "Obligations",
    payments: "Payments",
    settlementReport: "Settlement report",
    demoEnvironment: "Demo environment",
    localBrowserStorage: "Local browser storage",
    firebaseFirestore: "Firebase / Firestore",
    firebaseBackedRegister: "Firebase-backed register",
    localFallback: "Local fallback",
    cloudEnvironment: "Cloud environment",
    firestorePersistence: "Firestore persistence",
    localDemoFallbackHeading: "Local demo fallback",
    settlementOverview: "Settlement overview",
    overviewDescription: "A compact view of obligations, payments and the current open balance.",
    registerObligation: "Register obligation",
    recentObligations: "Recent obligations",
    openRegister: "Open register",
    coreWorkflow: "Core workflow",
    counterparty: "Counterparty",
    supplierContractorRecord: "Supplier or contractor record",
    contract: "Contract",
    termsResponsibleParty: "Terms and responsible party",
    obligation: "Obligation",
    documentAmountDueDate: "Document, amount and due date",
    paymentAndReport: "Payment and report",
    partialPaymentBalance: "Partial payment and balance",
    maintainDirectory: "Maintain the small directory used by contracts and settlement reports.",
    addCounterparty: "Add counterparty",
    addContract: "Add contract",
    close: "Close",
    newCounterparty: "New counterparty",
    supplierOrContractor: "Supplier or contractor",
    nameRequired: "Name *",
    typeRequired: "Type *",
    testRegistrationNumber: "Test registration number",
    contactReference: "Contact reference",
    exampleVolga: "Example: Volga Office Supply",
    saveCounterparty: "Save counterparty",
    directory: "Directory",
    newContract: "New contract",
    contractsDescription: "Link a simple contract record to each supplier or contractor.",
    rubOnly: "RUB only",
    selectCounterparty: "Select counterparty",
    contractNumberRequired: "Contract number *",
    contractDateRequired: "Contract date *",
    paymentTermsDays: "Payment terms, days",
    description: "Description",
    contractDescriptionPlaceholder: "Goods or work covered by the contract",
    saveContract: "Save contract",
    contractRegister: "Contract register",
    registerDocumentDetails: "Register the source-document details and amount that create a settlement obligation.",
    addObligation: "Add obligation",
    newObligation: "New obligation",
    documentMetadataEmbedded: "Document metadata is embedded here",
    selectContract: "Select contract",
    documentTypeRequired: "Document type *",
    documentNumberRequired: "Document number *",
    documentDateRequired: "Document date *",
    recognitionDateRequired: "Recognition date *",
    amountRubRequired: "Amount, RUB *",
    dueDateRequired: "Due date *",
    saveObligation: "Save obligation",
    activeRecords: ({ count }) => `${count} active records`,
    obligationRegister: "Obligation register",
    recordPaymentDescription: "Record one payment against one obligation. Several payments can settle one obligation.",
    addPayment: "Add payment",
    newPayment: "New payment",
    overpaymentsBlocked: "Overpayments are blocked",
    selectOpenObligation: "Select open obligation",
    paymentDateRequired: "Payment date *",
    paymentAmountRequired: "Amount, RUB *",
    methodRequired: "Method *",
    reference: "Reference",
    savePayment: "Save payment",
    paymentRegister: "Payment register",
    filterReportDescription: "Filter the compact register and inspect balances as of a selected date.",
    asOfSettlementRegister: "As-of settlement register",
    dueTodayNotOverdue: "Due today is not treated as overdue. All totals are calculated from synthetic records.",
    asOfDate: "As-of date",
    datePlaceholder: "DD/MM/YYYY",
    invalidDateError: "Enter a valid date in the format DD/MM/YYYY.",
    supplierRemainingBalance: "Supplier remaining balance",
    contractorRemainingBalance: "Contractor remaining balance",
    counterpartyType: "Counterparty type",
    allTypes: "All types",
    status: "Status",
    allStatuses: "All statuses",
    search: "Search",
    nameOrDocument: "Name or document",
    resetFilters: "Reset filters",
    filteredRegister: "Filtered register",
    records: ({ count }) => `${count} records`,
    obligationsLabel: "Obligations",
    registered: "registered",
    paid: "Paid",
    recordedPayments: "Recorded payments",
    remaining: "Remaining",
    openBalance: "Open balance",
    overdue: "Overdue",
    atDate: ({ date }) => `At ${date}`,
    name: "Name",
    type: "Type",
    testRegistration: "Test registration",
    contractsCount: "Contracts",
    number: "Number",
    date: "Date",
    terms: "Terms",
    document: "Document",
    dueDate: "Due date",
    amount: "Amount",
    paymentDate: "Payment date",
    method: "Method",
    statusColumn: "Status",
    noCounterparties: "No counterparties yet",
    addSupplierContractor: "Add a supplier or contractor to begin.",
    noContracts: "No contracts yet",
    addContractAfterCounterparty: "Add a contract after creating a counterparty.",
    noMatchingObligations: "No matching obligations",
    tryAnotherFilter: "Try another filter or register a new obligation.",
    noPayments: "No payments yet",
    registerPaymentOpenObligation: "Register a payment against an open obligation.",
    unknown: "Unknown",
    loadingSettlementData: "Loading settlement data",
    readingCurrentRegister: "Reading the current register from the selected data source.",
    dataLoadFailed: "Settlement data could not be loaded",
    retry: "Retry",
    savedToFirestore: "Saved to Firestore.",
    savedToLocalFallback: "Saved to the local demo fallback.",
    syntheticDataReset: "Synthetic data reset.",
    nameTypeRequiredError: "Name and type are required.",
    counterpartyNumberDateRequiredError: "Counterparty, number and date are required.",
    validCounterpartyError: "Select a valid counterparty.",
    completeObligationFieldsError: "Complete all required obligation fields.",
    validLinkedRecordsError: "Select valid linked records.",
    contractOtherCounterpartyError: "The contract belongs to another counterparty.",
    obligationAmountPositiveError: "The obligation amount must be greater than zero.",
    dueDateRecognitionError: "Due date cannot precede recognition date.",
    obligationPaymentDateRequiredError: "Obligation and payment date are required.",
    validObligationError: "Select a valid obligation.",
    paymentAmountPositiveError: "The payment amount must be greater than zero.",
    paymentOverLimitError: ({ amount }) => `Payment cannot exceed the remaining balance of ${amount}.`,
    dataServiceNotReadyError: "The data service is not ready.",
    sessionExpiredError: "Your session has expired. Sign in again.",
    firebaseInitializationError: ({ message }) => `Firebase initialization failed: ${message}`,
    authFailedError: "Firebase sign-in failed. Check the operator credentials and try again.",
    permissionDeniedError: "Firebase denied this operation. Check the authenticated session and Firestore rules.",
    firestoreLoadFailedError: "Firestore data could not be loaded. Check the connection and Firestore rules.",
    signInBeforeLoadingError: "Sign in before loading Firestore data.",
    switchToRussian: "Switch to Russian",
    switchToEnglish: "Switch to English",
    russianLanguage: "Russian",
    englishLanguage: "English",
    supplier: "Supplier",
    contractor: "Contractor",
    invoice: "Invoice",
    deliveryNote: "Delivery note",
    completedWorkAct: "Completed-work act",
    adjustment: "Adjustment",
    registeredStatus: "Registered",
    partiallyPaidStatus: "Partially paid",
    paidStatus: "Paid",
    overdueStatus: "Overdue",
    bankTransfer: "Bank transfer",
    cash: "Cash",
    other: "Other",
    days: ({ count }) => `${count} days`
  },
  ru: {
    automatedProcessing: "Автоматизированная обработка расчетов",
    appTitle: "Реестр расчетов",
    appSubtitle: "Компактный прототип учета расчетов с поставщиками и подрядчиками.",
    metaDescription: "Синтетический реестр расчетов с поставщиками и подрядчиками",
    preparingConnection: "Подготовка соединения",
    checkingConfiguration: "Проверка конфигурации Firebase для этого развертывания.",
    firebaseOperatorSignIn: "Вход оператора через Firebase",
    syntheticAccountHint: "Используйте синтетическую учетную запись изолированного проекта.",
    localDemoFallback: "Локальный демонстрационный режим",
    localFallbackHint: "Конфигурация Firebase отсутствует; записи сохраняются только в этом браузере.",
    operatorEmail: "Электронная почта оператора",
    password: "Пароль",
    signInWithFirebase: "Войти через Firebase",
    enterLocalDemo: "Войти в локальный демонстрационный режим",
    syntheticPasswordHint: "Используйте только синтетическую учетную запись оператора. Пароль не сохраняется приложением.",
    supplierContractorSettlements: "Расчеты с поставщиками и подрядчиками",
    operator: "Оператор",
    reset: "Сбросить",
    resetLocalSyntheticData: "Сбросить локальные синтетические данные",
    exit: "Выйти",
    primaryNavigation: "Основная навигация",
    overview: "Обзор",
    counterparties: "Контрагенты",
    contracts: "Договоры",
    obligations: "Обязательства",
    payments: "Платежи",
    settlementReport: "Отчет по расчетам",
    demoEnvironment: "Демонстрационная среда",
    localBrowserStorage: "Локальное хранилище браузера",
    firebaseFirestore: "Firebase / Firestore",
    firebaseBackedRegister: "Реестр на базе Firebase",
    localFallback: "Локальный режим",
    cloudEnvironment: "Облачная среда",
    firestorePersistence: "Хранение в Firestore",
    localDemoFallbackHeading: "Локальный демонстрационный режим",
    settlementOverview: "Обзор расчетов",
    overviewDescription: "Компактное представление обязательств, платежей и текущего открытого остатка.",
    registerObligation: "Зарегистрировать обязательство",
    recentObligations: "Последние обязательства",
    openRegister: "Открыть реестр",
    coreWorkflow: "Основной процесс",
    counterparty: "Контрагент",
    supplierContractorRecord: "Запись поставщика или подрядчика",
    contract: "Договор",
    termsResponsibleParty: "Условия и ответственная сторона",
    obligation: "Обязательство",
    documentAmountDueDate: "Документ, сумма и срок оплаты",
    paymentAndReport: "Платеж и отчет",
    partialPaymentBalance: "Частичный платеж и остаток",
    maintainDirectory: "Ведение небольшого справочника для договоров и отчетов по расчетам.",
    addCounterparty: "Добавить контрагента",
    addContract: "Добавить договор",
    close: "Закрыть",
    newCounterparty: "Новый контрагент",
    supplierOrContractor: "Поставщик или подрядчик",
    nameRequired: "Наименование *",
    typeRequired: "Тип *",
    testRegistrationNumber: "Тестовый регистрационный номер",
    contactReference: "Контактная информация",
    exampleVolga: "Например: Volga Office Supply",
    saveCounterparty: "Сохранить контрагента",
    directory: "Справочник",
    newContract: "Новый договор",
    contractsDescription: "Свяжите договор с каждым поставщиком или подрядчиком.",
    rubOnly: "Только RUB",
    selectCounterparty: "Выберите контрагента",
    contractNumberRequired: "Номер договора *",
    contractDateRequired: "Дата договора *",
    paymentTermsDays: "Срок оплаты, дней",
    description: "Описание",
    contractDescriptionPlaceholder: "Товары или работы по договору",
    saveContract: "Сохранить договор",
    contractRegister: "Реестр договоров",
    registerDocumentDetails: "Регистрация реквизитов первичного документа и суммы, создающих обязательство по расчетам.",
    addObligation: "Добавить обязательство",
    newObligation: "Новое обязательство",
    documentMetadataEmbedded: "Реквизиты документа включены в форму",
    selectContract: "Выберите договор",
    documentTypeRequired: "Тип документа *",
    documentNumberRequired: "Номер документа *",
    documentDateRequired: "Дата документа *",
    recognitionDateRequired: "Дата признания *",
    amountRubRequired: "Сумма, RUB *",
    dueDateRequired: "Срок оплаты *",
    saveObligation: "Сохранить обязательство",
    activeRecords: ({ count }) => `Активные записи — ${count} шт.`,
    obligationRegister: "Реестр обязательств",
    recordPaymentDescription: "Регистрация одного платежа по одному обязательству. Одно обязательство можно погашать несколькими платежами.",
    addPayment: "Добавить платеж",
    newPayment: "Новый платеж",
    overpaymentsBlocked: "Переплата блокируется",
    selectOpenObligation: "Выберите открытое обязательство",
    paymentDateRequired: "Дата платежа *",
    paymentAmountRequired: "Сумма, RUB *",
    methodRequired: "Способ *",
    reference: "Назначение или ссылка",
    savePayment: "Сохранить платеж",
    paymentRegister: "Реестр платежей",
    filterReportDescription: "Фильтрация компактного реестра и просмотр остатков на выбранную дату.",
    asOfSettlementRegister: "Реестр расчетов на дату",
    dueTodayNotOverdue: "Обязательство со сроком сегодня не считается просроченным. Все итоги рассчитаны по синтетическим данным.",
    asOfDate: "Дата отчета",
    datePlaceholder: "ДД.ММ.ГГГГ",
    invalidDateError: "Введите корректную дату в формате ДД.ММ.ГГГГ.",
    supplierRemainingBalance: "Остаток по поставщикам",
    contractorRemainingBalance: "Остаток по подрядчикам",
    counterpartyType: "Тип контрагента",
    allTypes: "Все типы",
    status: "Статус",
    allStatuses: "Все статусы",
    search: "Поиск",
    nameOrDocument: "Наименование или документ",
    resetFilters: "Сбросить фильтры",
    filteredRegister: "Отфильтрованный реестр",
    records: ({ count }) => `Записи — ${count} шт.`,
    obligationsLabel: "Обязательства",
    registered: "зарегистрировано",
    paid: "Оплачено",
    recordedPayments: "Зарегистрированные платежи",
    remaining: "Остаток",
    openBalance: "Открытый остаток",
    overdue: "Просрочено",
    atDate: ({ date }) => `На дату ${date}`,
    name: "Наименование",
    type: "Тип",
    testRegistration: "Тестовый регистрационный номер",
    contractsCount: "Договоры",
    number: "Номер",
    date: "Дата",
    terms: "Условия",
    document: "Документ",
    dueDate: "Срок оплаты",
    amount: "Сумма",
    paymentDate: "Дата платежа",
    method: "Способ",
    statusColumn: "Статус",
    noCounterparties: "Контрагенты отсутствуют",
    addSupplierContractor: "Добавьте поставщика или подрядчика, чтобы начать работу.",
    noContracts: "Договоры отсутствуют",
    addContractAfterCounterparty: "Добавьте договор после создания контрагента.",
    noMatchingObligations: "Подходящие обязательства отсутствуют",
    tryAnotherFilter: "Измените фильтр или зарегистрируйте новое обязательство.",
    noPayments: "Платежи отсутствуют",
    registerPaymentOpenObligation: "Зарегистрируйте платеж по открытому обязательству.",
    unknown: "Неизвестно",
    loadingSettlementData: "Загрузка данных по расчетам",
    readingCurrentRegister: "Чтение текущего реестра из выбранного источника данных.",
    dataLoadFailed: "Не удалось загрузить данные по расчетам",
    retry: "Повторить",
    savedToFirestore: "Сохранено в Firestore.",
    savedToLocalFallback: "Сохранено в локальном демонстрационном режиме.",
    syntheticDataReset: "Синтетические данные сброшены.",
    nameTypeRequiredError: "Укажите наименование и тип.",
    counterpartyNumberDateRequiredError: "Укажите контрагента, номер и дату.",
    validCounterpartyError: "Выберите действительного контрагента.",
    completeObligationFieldsError: "Заполните все обязательные поля обязательства.",
    validLinkedRecordsError: "Выберите действительные связанные записи.",
    contractOtherCounterpartyError: "Договор принадлежит другому контрагенту.",
    obligationAmountPositiveError: "Сумма обязательства должна быть больше нуля.",
    dueDateRecognitionError: "Срок оплаты не может быть раньше даты признания.",
    obligationPaymentDateRequiredError: "Укажите обязательство и дату платежа.",
    validObligationError: "Выберите действительное обязательство.",
    paymentAmountPositiveError: "Сумма платежа должна быть больше нуля.",
    paymentOverLimitError: ({ amount }) => `Платеж не может превышать остаток ${amount}.`,
    dataServiceNotReadyError: "Источник данных еще не готов.",
    sessionExpiredError: "Сеанс завершен. Войдите снова.",
    firebaseInitializationError: ({ message }) => `Не удалось инициализировать Firebase: ${message}`,
    authFailedError: "Не удалось войти через Firebase. Проверьте данные оператора и повторите попытку.",
    permissionDeniedError: "Firebase отклонил операцию. Проверьте сеанс и правила Firestore.",
    firestoreLoadFailedError: "Не удалось загрузить данные Firestore. Проверьте соединение и правила Firestore.",
    signInBeforeLoadingError: "Войдите перед загрузкой данных Firestore.",
    switchToRussian: "Переключить на русский",
    switchToEnglish: "Переключить на английский",
    russianLanguage: "Русский",
    englishLanguage: "Английский",
    supplier: "Поставщик",
    contractor: "Подрядчик",
    invoice: "Счет-фактура",
    deliveryNote: "Товарная накладная",
    completedWorkAct: "Акт выполненных работ",
    adjustment: "Корректировка",
    registeredStatus: "Зарегистрировано",
    partiallyPaidStatus: "Частично оплачено",
    paidStatus: "Оплачено",
    overdueStatus: "Просрочено",
    bankTransfer: "Банковский перевод",
    cash: "Наличные",
    other: "Другое",
    days: ({ count }) => `${count} дн.`
  }
};

export function localeFromPath(pathname) {
  const segment = pathname.split("/").filter(Boolean)[0];
  return SUPPORTED_LOCALES.includes(segment) ? segment : DEFAULT_LOCALE;
}

export function localePath(locale) {
  const selected = SUPPORTED_LOCALES.includes(locale) ? locale : DEFAULT_LOCALE;
  return `/${selected}/`;
}

export function localeUrl(locale, origin = globalThis.location?.origin || "") {
  return `${origin}${localePath(locale)}`;
}

export function formatDateValue(value, locale) {
  if (!value) return "—";
  if (locale === "ru") {
    const [year, month, day] = value.split("-");
    return `${day}.${month}.${year}`;
  }
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`));
}

export function translate(locale, key, values = {}) {
  const selected = messages[locale]?.[key] ?? messages.en[key] ?? key;
  if (typeof selected === "function") return selected(values);
  return selected.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? "");
}

export function translateText(value, locale) {
  let result = value;
  const entries = Object.entries(messages.en)
    .filter(([, text]) => typeof text === "string" && text.length > 0)
    .sort(([, first], [, second]) => second.length - first.length);
  for (const [key, english] of entries) {
    const translated = translate(locale, key);
    if (translated !== english) result = result.split(english).join(translated);
  }
  result = result.replace(/(\d+) active records/g, (_, count) => translate(locale, "activeRecords", { count }));
  result = result.replace(/(\d+) records/g, (_, count) => translate(locale, "records", { count }));
  result = result.replace(/(\d+) days/g, (_, count) => translate(locale, "days", { count }));
  return result;
}

export function dictionaryKeys(locale) {
  return Object.keys(messages[locale] || {});
}
